version: '3.1'

services:

  db:
    image: mariadb:10.9.4-jammy
    restart: always
    ports:
      - 8081:80
    networks:
      - wp
    expose:
      - 3306
      - 33060
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=mypass
    volumes:
      # './' tells docker-compose to use $WORKDIR
      - ./db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    restart: always
    depends_on:
      - db
    ports:
      - 80:80 #Wordpress multisite requires port 80
    networks:
      - wp
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=mypass
    volumes:
     # './' tells docker-compose to use $WORKDIR
      - ./wp_data:/var/www/html
      - ./wp_themes:/var/www/html/wp-content/themes/
      - ./wp_plugins:/var/www/html/wp-content/plugins/

networks:
  wp:

volumes:
  db_data:
  wp_data:
  wp_themes:
  wp_plugins:
