services:
  wordpress:
    image: wordpress:php8.3-apache
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_data:/var/www/html
      - ./wp_themes:/var/www/html/wp-content/themes/
      - ./wp_plugins:/var/www/html/wp-content/plugins/
    depends_on:
      - db
    networks:
        - wp

  db:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
        - wp

  nginx:
    image: nginx:1.27.2-perl
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - wordpress
    networks:
        - wp

networks:
  wp:

volumes:
  db_data:
  wp_data:
  wp_themes:
  wp_plugins:
